### ISSUE TITLE
No Matching Indices - Debian

### ISSUE THREAD

**Issue by PhoenixNP** [outflanknl/RedELK#232]
The latest code-base appears to have a issue with all indexing/indices except redirtraffic-*, redelk-modules, redelk-iplist-tor and redelk-iplist-redteam.
This means that most of the dashboards currently don't work but only throw errors like;

No matching indices found: No indices match pattern "rtops-*"

This has been tested on both Debian 10 and Debian 11.

**Comment by carlneuhaus** [comment]
A commit was made, 0322e71f7fe37b6c658ae6ea3d7da1bbebd8f4e6, that removed the Logstash configs from being included in the Docker build.
Adding these two lines to the docker-compose.yml file in elkserver, under logstash volumes, should address the issue
```
- ./docker/redelk-logstash/redelkinstalldata/redelk-main/:/usr/share/logstash/redelk-main
- ./docker/redelk-logstash/redelkinstalldata/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
```

**Comment by MarcOverIP** [comment]
Not sure I get the error. Please provide more details.

Some background info: the indices are precreated by use of index templates. These are imported upon initial install for you by the redelk-base docker. This has to be done upon initial install, as the ES data is in a local docker volume and thus can't be shipped with the docker image.

The log file ``elkserver/mounts/redelk-logs/redelk-docker-init.log`` should show you if for some reason this container didn't go through its normal init steps. If there is an error there, we surely want to investigate!

**Comment by PhoenixNP** [comment]
I should have formulated the issue better.
The indices and patterns are created, but the Cobalt-Strike teamserver data/logs is not placed into them.
The cronjobs are working fine and will copy the data to the elkserver, but nothing more happens after that.

I haven't seen any errors in the redelk-docker-init.log file.

**Comment by MarcOverIP** [comment]
Ah, so it could also be a c2server-elkserver connect problem. Please check for errors in the logs from docker redelk-logstash (``docker logs redelk-logstash``) and from the filebeat daemon on your c2server (``/var/log/filebeat`` or any other place nowadays filebeat logs are stored on Debian). 

If there is no issue in there and if you so a clear log message that the connection between filebeat and logstash is ok, than the next step would be the connection between logstash and elasticsearch. The redelk-logstash container log should also give out that info, or otherwise ``docker logs redelk-elasticsearch`` is a valid source.

**Comment by PhoenixNP** [comment]
Heya @MarcOverIP,

I/we have figured out the issue! =)
Apparently one of the firewalls had traffic inspection enabled and was dropping the logstash traffic due to a unknown certificate *sigh*

Thank you for the help! =)
