### ISSUE TITLE
Logstash full cert path as variable

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#85]
In the current setup, only the folder containing the certificates can be passed as an environment variable.

This should be changed to add the possibility to pass the full path to the certificate, ca and key files instead.

**Comment by MarcOverIP** [comment]
Well, I did think about this right before I made the setup as it is right now. With Docker's issues regarding mounting a file instead of a directory, when a file changes, the docker container looses the mapping to the file. When you are mounting the directory instead of the files, you can (at least in theory, have not tested this) swap files on the fly. I believe this is a feature that can come in handy for some use cases.

**Comment by fastlorenzo** [comment]
Just to clarify, I'm not talking about changing the mount, this would still be a folder. It's more changing the reference to the certificate path (to removed the hardcoded part that is currently built in the container)

**Comment by MarcOverIP** [comment]
Clear. Done in #86
